version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: jita
      POSTGRES_USER: jita
      POSTGRES_PASSWORD: jita
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:5
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8001:80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin:
