services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: jita
      POSTGRES_USER: jita
      POSTGRES_PASSWORD: jita
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/schemas:/docker-entrypoint-initdb.d

  adminer:
    depends_on:
      - postgres
    image: adminer:latest
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres-data:
