apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: naisdevice-jita
  namespace: naisdevice
  labels:
    team: naisdevice
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
    {{/each}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  envFrom:
    - secret: naisdevice-jita
  gcp:
    sqlInstances:
      - name: naisdevice-jita
        type: POSTGRES_12
        tier: {{ db.tier }}
        cascadingDelete: {{ db.cascadingDelete }}
        highAvailability: {{ db.highAvailability }}
        databases:
          - name: naisdevice-jita
            envVarPrefix: DB
