name: Build and deploy
on:
  workflow_dispatch:
  push:
permissions:
  contents: read
  id-token: write
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2 # ratchet:nais/docker-build-push@main
        id: docker-build-push
        with:
          team: nais
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-prod-gcp:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy to prod-gcp
    needs:
      - build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yml
          VAR: image=${{ needs.build-and-push.outputs.image }}
          TELEMETRY: ${{ needs.build-and-push.outputs.telemetry }}
